#!/usr/bin/env python3
"""Update only the no-russia rule list; Python standard library only."""

import re
from pathlib import Path
from urllib.request import urlopen


SOURCE = "https://raw.githubusercontent.com/dartraiden/no-russia-hosts/master/hosts.txt"
TARGET = Path(__file__).resolve().parents[1] / "shadowrocket/no-russia.list"
LABEL = re.compile(r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?")


def convert(text):
    domains = set()
    for number, line in enumerate(text.splitlines(), 1):
        domain = line.split("#", 1)[0].strip().lower()
        if not domain:
            continue
        labels = domain.split(".")
        if (len(domain) > 253 or len(labels) < 2 or labels[-1].isdigit()
                or not all(LABEL.fullmatch(label) for label in labels)):
            raise ValueError(f"Invalid domain on upstream line {number}")
        domains.add(domain)
    if not domains:
        raise ValueError("Upstream contains no domains")
    return (f"# Source: {SOURCE}\n"
            "# Generated by scripts/update-no-russia.py; do not edit manually.\n"
            + "".join(f"DOMAIN-SUFFIX,{domain}\n" for domain in sorted(domains)))


if __name__ == "__main__":
    with urlopen(SOURCE, timeout=30) as response:
        result = convert(response.read().decode("utf-8-sig"))
    temporary = TARGET.with_suffix(".list.tmp")
    temporary.write_text(result, encoding="utf-8")
    temporary.replace(TARGET)
